#!/usr/bin/env python3
"""
Generates every raster-free copy of the Kickoff mark.

The mark exists five times over - launcher foreground, launcher monochrome, splash,
in-app drawable, notification glyph - and once existed as five hand-edited XML files that
had already drifted apart from each other and from the Compose version. The geometry
constants below are the same numbers as ui/component/KickoffLogo.kt, so the mark is one
object with one definition and the files are output, not source.

    python3 tools/logo/generate_logo.py

Writes into app/src/main/res/drawable/. Re-run it after changing anything here.
"""
from __future__ import annotations

import math
import pathlib

# ---- geometry (mirrors KickoffLogo.kt) --------------------------------------------------
RING_RADIUS = 0.360
RING_STROKE = 0.118
GAP_CENTER_DEG = -45.0
GAP_HALF_DEG = 34.0
ARC_START_DEG = GAP_CENTER_DEG - GAP_HALF_DEG
ARC_SWEEP_DEG = -(360.0 - 2 * GAP_HALF_DEG)

DOT_RADIUS = 0.094
DOT_ANGLE_DEG = -40.0
DOT_ORBIT = RING_RADIUS + 0.02

BALL_RADIUS = 0.222
PENTAGON_OF_BALL = 0.40
PANEL_ORBIT_OF_BALL = 0.68
PANEL_RX_OF_BALL = 0.30
PANEL_RY_OF_BALL = 0.17
PANEL_ANGLES = (-90.0, -18.0, 54.0, 126.0, 198.0)

# ---- colour -----------------------------------------------------------------------------
GREEN = "#FF0A7233"
BALL_WHITE = "#FFFFFFFF"
BALL_BLACK = "#FF14181A"
BALL_RIM = "#33000000"

RES = pathlib.Path(__file__).resolve().parents[2] / "app/src/main/res/drawable"
HEADER = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    "<!-- Generated by tools/logo/generate_logo.py. Do not edit; edit the generator. -->\n"
)


def f(value: float) -> str:
    return f"{value:.2f}"


def polar(cx: float, cy: float, radius: float, degrees: float) -> tuple[float, float]:
    rad = math.radians(degrees)
    return cx + radius * math.cos(rad), cy + radius * math.sin(rad)


def ring_path(c: float, s: float) -> str:
    """The open arc, in two sub-180 degree hops so the flags stay unambiguous."""
    radius = RING_RADIUS * s
    steps = 2
    per = ARC_SWEEP_DEG / steps
    x, y = polar(c, c, radius, ARC_START_DEG)
    out = [f"M{f(x)},{f(y)}"]
    for i in range(1, steps + 1):
        x, y = polar(c, c, radius, ARC_START_DEG + per * i)
        # large-arc 0, sweep 0: each hop is under 180 degrees and runs anticlockwise.
        out.append(f"A{f(radius)},{f(radius)},0,0,0,{f(x)},{f(y)}")
    return " ".join(out)


def circle_path(cx: float, cy: float, radius: float) -> str:
    return (
        f"M{f(cx - radius)},{f(cy)} "
        f"a{f(radius)},{f(radius)},0,1,0,{f(radius * 2)},0 "
        f"a{f(radius)},{f(radius)},0,1,0,{f(-radius * 2)},0Z"
    )


def pentagon_path(cx: float, cy: float, radius: float) -> str:
    points = [polar(cx, cy, radius, deg) for deg in PANEL_ANGLES]
    head = f"M{f(points[0][0])},{f(points[0][1])}"
    rest = "".join(f"L{f(x)},{f(y)}" for x, y in points[1:])
    return head + rest + "Z"


def panel_paths(cx: float, cy: float, ball: float) -> list[str]:
    """The five outer panels: ellipses laid tangentially just inside the rim."""
    rx, ry = ball * PANEL_RX_OF_BALL, ball * PANEL_RY_OF_BALL
    out = []
    for deg in PANEL_ANGLES:
        ex, ey = polar(cx, cy, ball * PANEL_ORBIT_OF_BALL, deg + 36.0)
        rot = deg + 36.0 + 90.0
        ax, ay = polar(ex, ey, rx, rot)
        bx, by = polar(ex, ey, rx, rot + 180.0)
        out.append(
            f"M{f(ax)},{f(ay)} A{f(rx)},{f(ry)},{f(rot)},1,0,{f(bx)},{f(by)} "
            f"A{f(rx)},{f(ry)},{f(rot)},1,0,{f(ax)},{f(ay)}Z"
        )
    return out


def satellite_centre(c: float, s: float) -> tuple[float, float, float]:
    x, y = polar(c, c, DOT_ORBIT * s, DOT_ANGLE_DEG)
    return x, y, DOT_RADIUS * s


def ball_layers(c: float, s: float, rim: bool) -> list[str]:
    """White sphere, black pentagon, five black panels - a football, not a silhouette."""
    ball = BALL_RADIUS * s
    layers = [
        f'    <path android:pathData="{circle_path(c, c, ball)}" '
        f'android:fillColor="{BALL_WHITE}" />'
    ]
    layers.append(
        f'    <path android:pathData="{pentagon_path(c, c, ball * PENTAGON_OF_BALL)}" '
        f'android:fillColor="{BALL_BLACK}" />'
    )
    for path in panel_paths(c, c, ball):
        layers.append(f'    <path android:pathData="{path}" android:fillColor="{BALL_BLACK}" />')
    if rim:
        layers.append(
            f'    <path android:pathData="{circle_path(c, c, ball)}" '
            f'android:strokeColor="{BALL_RIM}" android:strokeWidth="{f(ball * 0.07)}" />'
        )
    return layers


def hollow_ball_layer(c: float, s: float, colour: str) -> str:
    """One even-odd path: the sphere with its panels punched out, for tinted icons.

    A monochrome icon is an alpha mask - black panels drawn on top would take the same
    tint as the sphere and vanish. Holes survive tinting; that is the only way the ball
    still reads as a ball on the themed launcher icon.
    """
    ball = BALL_RADIUS * s
    parts = [circle_path(c, c, ball), pentagon_path(c, c, ball * PENTAGON_OF_BALL)]
    parts.extend(panel_paths(c, c, ball))
    return (
        f'    <path android:fillType="evenOdd" android:pathData="{" ".join(parts)}" '
        f'android:fillColor="{colour}" />'
    )


def vector(viewport: float, scale: float, body: list[str], size_dp: int) -> str:
    return (
        HEADER
        + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{size_dp}dp" android:height="{size_dp}dp"\n'
        f'    android:viewportWidth="{f(viewport)}" android:viewportHeight="{f(viewport)}">\n'
        + "\n".join(body)
        + "\n</vector>\n"
    )


def ring_layer(c: float, s: float, colour: str) -> str:
    return (
        f'    <path android:pathData="{ring_path(c, s)}"\n'
        f'        android:strokeColor="{colour}" android:strokeWidth="{f(RING_STROKE * s)}"\n'
        f'        android:strokeLineCap="round" />'
    )


def satellite_layers(c: float, s: float, rim: bool) -> list[str]:
    x, y, r = satellite_centre(c, s)
    out = [
        f'    <path android:pathData="{circle_path(x, y, r)}" '
        f'android:fillColor="{BALL_WHITE}" />'
    ]
    if rim:
        out.append(
            f'    <path android:pathData="{circle_path(x, y, r)}" '
            f'android:strokeColor="{BALL_RIM}" android:strokeWidth="{f(r * 0.16)}" />'
        )
    return out


def full_mark(viewport: float, scale: float, size_dp: int, rim: bool) -> str:
    c = viewport / 2
    body = ball_layers(c, scale, rim)
    body.append(ring_layer(c, scale, GREEN))
    body.extend(satellite_layers(c, scale, rim))
    return vector(viewport, scale, body, size_dp)


def tinted_mark(viewport: float, scale: float, size_dp: int, hollow: bool) -> str:
    """The single-colour cut of the mark, for the monochrome icon and the status bar."""
    c = viewport / 2
    x, y, r = satellite_centre(c, scale)
    body = [
        hollow_ball_layer(c, scale, BALL_WHITE)
        if hollow
        else f'    <path android:pathData="{circle_path(c, c, BALL_RADIUS * scale)}" '
        f'android:fillColor="{BALL_WHITE}" />',
        ring_layer(c, scale, BALL_WHITE),
        f'    <path android:pathData="{circle_path(x, y, r)}" '
        f'android:fillColor="{BALL_WHITE}" />',
    ]
    return vector(viewport, scale, body, size_dp)


def splash() -> str:
    """The launcher mark again, but with the three parts named so the AVD can drive them."""
    viewport, scale, c = 108.0, 62.0, 54.0
    x, y, r = satellite_centre(c, scale)
    body = [
        '    <group android:name="ball_group" android:pivotX="54" android:pivotY="54">',
        *["    " + line for line in ball_layers(c, scale, rim=True)],
        "    </group>",
        f'    <path android:name="ring" android:pathData="{ring_path(c, scale)}"\n'
        f'        android:strokeColor="{GREEN}" android:strokeWidth="{f(RING_STROKE * scale)}"\n'
        f'        android:strokeLineCap="round" android:trimPathEnd="0" />',
        f'    <group android:name="dot_group" android:pivotX="{f(x)}" android:pivotY="{f(y)}"\n'
        f'        android:scaleX="0" android:scaleY="0">',
        f'        <path android:pathData="{circle_path(x, y, r)}" '
        f'android:fillColor="{BALL_WHITE}" />',
        "    </group>",
    ]
    return vector(viewport, scale, body, 108)


def main() -> None:
    files = {
        # Launcher foreground: a light background behind it, and the mark has to stay
        # inside the adaptive-icon safe zone, hence the 62/108 scale.
        "ic_launcher_foreground.xml": full_mark(108.0, 62.0, 108, rim=True),
        "ic_launcher_monochrome.xml": tinted_mark(108.0, 62.0, 108, hollow=True),
        # Status bar: 24dp, where panel holes turn to mush - a plain ball is what reads.
        "ic_stat_kickoff.xml": tinted_mark(24.0, 23.0, 24, hollow=False),
        "kickoff_splash_vector.xml": splash(),
    }
    for name, content in files.items():
        (RES / name).write_text(content)
        print(f"wrote {name}")


if __name__ == "__main__":
    main()
