package com.tzvi.kickoff.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Kickoff brand palette.
 *
 * Generated from the brand seed #00C853 ("pitch green") with the Material 3
 * `Content` scheme variant, which keeps the seed itself as `primaryContainer`
 * and holds the neutral surfaces close to true neutral so scorelines and crests
 * stay the loudest thing on screen.
 *
 * Do not hand-edit individual values: regenerate the whole scheme if the seed
 * changes, or the tonal relationships (and therefore the contrast ratios) break.
 */

internal val primaryLight = Color(0xFF006E2A)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFF00C853)
internal val onPrimaryContainerLight = Color(0xFF004C1B)
internal val inversePrimaryLight = Color(0xFF3CE36A)
internal val secondaryLight = Color(0xFF256B34)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFA7F1AB)
internal val onSecondaryContainerLight = Color(0xFF2A7038)
internal val tertiaryLight = Color(0xFF006397)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFF4EB5FF)
internal val onTertiaryContainerLight = Color(0xFF00456B)
internal val backgroundLight = Color(0xFFF3FCEE)
internal val onBackgroundLight = Color(0xFF151E15)
internal val surfaceLight = Color(0xFFF3FCEE)
internal val onSurfaceLight = Color(0xFF151E15)
internal val surfaceVariantLight = Color(0xFFD7E7D3)
internal val onSurfaceVariantLight = Color(0xFF3C4A3C)
internal val surfaceTintLight = Color(0xFF006E2A)
internal val inverseSurfaceLight = Color(0xFF2A3329)
internal val inverseOnSurfaceLight = Color(0xFFEAF4E5)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val outlineLight = Color(0xFF6C7B6A)
internal val outlineVariantLight = Color(0xFFBBCBB8)
internal val scrimLight = Color(0xFF000000)
internal val surfaceBrightLight = Color(0xFFF3FCEE)
internal val surfaceDimLight = Color(0xFFD3DDCF)
internal val surfaceContainerLight = Color(0xFFE7F1E3)
internal val surfaceContainerHighLight = Color(0xFFE1EBDD)
internal val surfaceContainerHighestLight = Color(0xFFDCE5D7)
internal val surfaceContainerLowLight = Color(0xFFEDF6E8)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val primaryFixedLight = Color(0xFF69FF87)
internal val primaryFixedDimLight = Color(0xFF3CE36A)
internal val onPrimaryFixedLight = Color(0xFF002108)
internal val onPrimaryFixedVariantLight = Color(0xFF00531E)
internal val secondaryFixedLight = Color(0xFFAAF4AD)
internal val secondaryFixedDimLight = Color(0xFF8ED793)
internal val onSecondaryFixedLight = Color(0xFF002108)
internal val onSecondaryFixedVariantLight = Color(0xFF02531E)
internal val tertiaryFixedLight = Color(0xFFCCE5FF)
internal val tertiaryFixedDimLight = Color(0xFF93CCFF)
internal val onTertiaryFixedLight = Color(0xFF001D31)
internal val onTertiaryFixedVariantLight = Color(0xFF004B73)

internal val primaryDark = Color(0xFF3FE56C)
internal val onPrimaryDark = Color(0xFF003912)
internal val primaryContainerDark = Color(0xFF00C853)
internal val onPrimaryContainerDark = Color(0xFF004C1B)
internal val inversePrimaryDark = Color(0xFF006E2A)
internal val secondaryDark = Color(0xFF8ED793)
internal val onSecondaryDark = Color(0xFF003912)
internal val secondaryContainerDark = Color(0xFF02531E)
internal val onSecondaryContainerDark = Color(0xFF7EC583)
internal val tertiaryDark = Color(0xFF98CEFF)
internal val onTertiaryDark = Color(0xFF003351)
internal val tertiaryContainerDark = Color(0xFF4EB5FF)
internal val onTertiaryContainerDark = Color(0xFF00456B)
internal val backgroundDark = Color(0xFF0D150D)
internal val onBackgroundDark = Color(0xFFDCE5D7)
internal val surfaceDark = Color(0xFF0D150D)
internal val onSurfaceDark = Color(0xFFDCE5D7)
internal val surfaceVariantDark = Color(0xFF3C4A3C)
internal val onSurfaceVariantDark = Color(0xFFBBCBB8)
internal val surfaceTintDark = Color(0xFF3CE36A)
internal val inverseSurfaceDark = Color(0xFFDCE5D7)
internal val inverseOnSurfaceDark = Color(0xFF2A3329)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val outlineDark = Color(0xFF869583)
internal val outlineVariantDark = Color(0xFF3C4A3C)
internal val scrimDark = Color(0xFF000000)
internal val surfaceBrightDark = Color(0xFF333B32)
internal val surfaceDimDark = Color(0xFF0D150D)
internal val surfaceContainerDark = Color(0xFF192219)
internal val surfaceContainerHighDark = Color(0xFF242C23)
internal val surfaceContainerHighestDark = Color(0xFF2E372E)
internal val surfaceContainerLowDark = Color(0xFF151E15)
internal val surfaceContainerLowestDark = Color(0xFF081008)
internal val primaryFixedDark = Color(0xFF69FF87)
internal val primaryFixedDimDark = Color(0xFF3CE36A)
internal val onPrimaryFixedDark = Color(0xFF002108)
internal val onPrimaryFixedVariantDark = Color(0xFF00531E)
internal val secondaryFixedDark = Color(0xFFAAF4AD)
internal val secondaryFixedDimDark = Color(0xFF8ED793)
internal val onSecondaryFixedDark = Color(0xFF002108)
internal val onSecondaryFixedVariantDark = Color(0xFF02531E)
internal val tertiaryFixedDark = Color(0xFFCCE5FF)
internal val tertiaryFixedDimDark = Color(0xFF93CCFF)
internal val onTertiaryFixedDark = Color(0xFF001D31)
internal val onTertiaryFixedVariantDark = Color(0xFF004B73)
